Chill\MainBundle\Entity\Center:
    type: entity
    table: centers
    id:
        id:
            type: integer
            id: true
            generator: 
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255