Chill\MainBundle\Entity\Country:
    type: entity
    table: null
    cache:
        usage: READ_ONLY
        region: country_cache_region
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: json_array
        countryCode:
            type: string
            length: 3
    lifecycleCallbacks: {  }
