Chill\MainBundle\Entity\GroupCenter:
    type: entity
    table: group_centers
    cache:
        usage: NONSTRICT_READ_WRITE
        region: acl_cache_region
    id:
        id:
            type: integer
            id: true
            generator: 
                strategy: AUTO
    manyToOne:
        center:
            targetEntity: Chill\MainBundle\Entity\Center
            inversedBy: groupCenters
            cache:
                usage: NONSTRICT_READ_WRITE
        permissionsGroup:
            targetEntity: Chill\MainBundle\Entity\PermissionsGroup
            cache:
                usage: NONSTRICT_READ_WRITE