Chill\MainBundle\Entity\GroupCenter:
    type: entity
    table: group_centers
    id:
        id:
            type: integer
            id: true
            generator: 
                strategy: AUTO
    manyToOne:
        center:
            targetEntity: Chill\MainBundle\Entity\Center
            inversedBy: groupCenters
        permissionsGroup:
            targetEntity: Chill\MainBundle\Entity\PermissionsGroup