Chill\MainBundle\Entity\Language:
    type: entity
    table: null
    cache:
        usage: READ_ONLY
        region: language_cache_region
    id: 
        id:
            type: string
    fields:
        name:
            type: json_array
    lifecycleCallbacks: {  }