Chill\MainBundle\Entity\PermissionGroup:
    type: entity
    table: permission_groups
    id:
        id:
            type: integer
            id: true
            generator: 
                strategy: AUTO
    fields:
        name:
            type: json_array
    manyToMany:
        roleScopes:
            targetEntity: Chill\MainBundle\Entity\RoleScope
            