Chill\MainBundle\Entity\RoleScope:
    type: entity
    table: role_scopes
    cache:
        usage: NONSTRICT_READ_WRITE
        region: acl_cache_region
    id:
        id:
            type: integer
            id: true
            generator: 
                strategy: AUTO
    fields:
        role:
            type: string
            length: 255
    manyToOne:
        scope:
            targetEntity: Chill\MainBundle\Entity\Scope
            inversedBy: roleScopes
            nullable: true
            cache:
                usage: NONSTRICT_READ_WRITE
                