Chill\MainBundle\Entity\Scope:
    type: entity
    table: scopes
    cache:
        usage: NONSTRICT_READ_WRITE
        region: acl_cache_region
    id:
        id:
            type: integer
            id: true
            generator: 
                strategy: AUTO
    fields:
        name:
            type: json_array
    oneToMany:
        roleScopes:
            targetEntity: Chill\MainBundle\Entity\RoleScope
            mappedBy: scope
            cache:
                usage: NONSTRICT_READ_WRITE