Chill\MainBundle\Entity\User:
    type: entity
    table: users
    cache:
        usage: NONSTRICT_READ_WRITE
        region: acl_cache_region
    id:
        id:
            type: integer
            id: true
            generator: 
                strategy: AUTO
    fields:
        username:
            type: string
            length: 80
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
            nullable: true
        enabled:
            type: boolean
            default: true
        locked:
            type: boolean
            default: false
    manyToMany:
        groupCenters:
            targetEntity: Chill\MainBundle\Entity\GroupCenter
            cache:
                usage: NONSTRICT_READ_WRITE
        
                    
