root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /homepage
        permanent: true

chill_main_homepage_without_locale:
    pattern:  /homepage
    defaults: { _controller: ChillMainBundle:Default:indexWithoutLocale }

chill_main_homepage:
    pattern:  /{_locale}/homepage
    defaults: { _controller: ChillMainBundle:Default:index }
    options:
        menus:
            section:
                order: 10
                label: Homepage
                icons: [home]

chill_main_admin_central:
    pattern: /{_locale}/admin
    defaults: { _controller: ChillMainBundle:Admin:index }
    options:
        menus:
            section:
                order: 20
                label: Admin Menu
                icons: [gears]
                
chill_main_search:
    pattern: /{_locale}/person/search
    defaults: { _controller: ChillMainBundle:Search:search }

login:
    path:     /login
    defaults: { _controller: ChillMainBundle:Login:login }

login_check:
    path:    /login_check

logout:
    path:    /logout
    options:
        menus:
            user:
                order: 10
                label: Logout
                icon: power-off