root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /welcome
        permanent: true
    options:
        menus:
            section:
                order: 10
                label: Homepage
                icon: home

cl_chill_main_homepage:
    pattern:  /welcome
    defaults: { _controller: ChillMainBundle:Default:index }

chill_main_admin_central:
    pattern: /admin
    defaults: { _controller: ChillMainBundle:Admin:index }
    options:
        menus:
            section:
                order: 20
                label: Admin Menu
                icon: gears

login:
    path:     /login
    defaults: { _controller: ChillMainBundle:Login:login }

login_check:
    path:    /login_check

logout:
    path:    /logout
    options:
        menus:
            user:
                order: 10
                label: Logout
                icon: power-off
