root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /welcome
        permanent: true
    options:
        menus:
            main:
                order: 10
                label: Homepage

cl_chill_main_homepage:
    pattern:  /welcome
    defaults: { _controller: ChillMainBundle:Default:index }

chill_main_admin_central:
    pattern: /admin
    defaults: { _controller: ChillMainBundle:Admin:index }
    options:
        menus:
            main:
                order: 20
                label: Admin Menu

login:
    path:     /login
    defaults: { _controller: ChillMainBundle:Login:login }

login_check:
    path:    /login_check

logout:
    path:    /logout
