root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /hello
        permanent: true
    options:
        menus:
            main:
                order: 10
                label: homepage

cl_chill_main_homepage:
    pattern:  /hello
    defaults: { _controller: ChillMainBundle:Default:index }
    
chill_main_admin_central:
    pattern: /admin
    defaults: { _controller: ChillMainBundle:Admin:index }
    options:
        menus:
            main:
                order: 20
                label: homepage

login:
    path:     /login
    defaults: { _controller: ChillMainBundle:Login:login }
