parameters:
#    cl_chill_main.example.class: Chill\MainBundle\Example

services:
    chill.main.menu_composer:
        class: Chill\MainBundle\Routing\MenuComposer
        #must be set in function to avoid circular reference with chill.main.twig.chill_menu
        calls:
            -  [setContainer, ["@service_container"]]

    chill.main.twig.chill_menu:
        class: Chill\MainBundle\Routing\MenuTwig
        arguments:
            - "@chill.main.menu_composer"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }

    chill.main.form.type.translatable.string:
        class: Chill\MainBundle\Form\Type\TranslatableStringFormType
        arguments:
            - "%chill_main.available_languages%"
            #- "%framework.translator.fallback%"
            - "%locale%"
        tags:
            - { name: form.type, alias: translatable_string }
     
    chill.main.form.type.select2choice:
        class: Chill\MainBundle\Form\Type\Select2ChoiceType
        tags:
            - {name: form.type, alias: select2_choice}
            
    chill.main.form.type.select2entity:
        class: Chill\MainBundle\Form\Type\Select2EntityType
        tags:
            - {name: form.type, alias: select2_entity }
            
    chill.main.form.type.select2country:
        class: Chill\MainBundle\Form\Type\Select2CountryType
        tags:
            - { name: form.type, alias: select2_chill_country }
