parameters:
#    cl_chill_main.example.class: CL\Chill\MainBundle\Example

services:
    chill.main.menu_composer:
        class: CL\Chill\MainBundle\Routing\MenuComposer
        #must be set in function to avoid circular reference with chill.main.twig.chill_menu
        calls:
            -  [setContainer, ["@service_container"]]
            
    chill.main.twig.chill_menu:
        class: CL\Chill\MainBundle\Routing\MenuTwig
        arguments:
            - "@chill.main.menu_composer"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }
