parameters:
#    cl_chill_main.example.class: CL\Chill\MainBundle\Example

services:
    chill.main.menu_composer:
        class: CL\Chill\MainBundle\Routing\MenuComposer
        arguments:
            -  "@router"
#    cl_chill_main.example:
#        class: %cl_chill_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
