Chill\MainBundle\Entity\PermissionsGroup:
    properties:
        name: 
            - NotBlank: ~
            - Length:
                max: 50
        roleScopes:
            - Valid: ~
    constraints:
        - Callback: [isRoleScopePresentOnce]
        
Chill\MainBundle\Entity\User:
    properties:
        username:
            - Length: 
                max: 70
                min: 3
    constraints:
        - Callback: [isGroupCenterPresentOnce]

Chill\MainBundle\Entity\RoleScope:
    constraints:
        - \Chill\MainBundle\Validation\Constraint\RoleScopeScopePresenceConstraint: ~
        
Chill\MainBundle\Entity\Center:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 50
                min: 3

Chill\MainBundle\Entity\Address:
    properties:
        streetAddress1:
            - Length:
                min: 2
                max: 250
        postcode:
            - NotNull: ~
        validFrom:
            - NotNull: ~
            - Date: ~
            
Chill\MainBundle\Entity\PostalCode:
    properties:
        name:
            - Length: 
                max: 250
                min: 2
        code:
            - Length:
                min: 2
                max: 100
        country:
            - NotNull: ~