Chill\MainBundle\Entity\PermissionsGroup:
    properties:
        name: 
            - NotBlank: ~
            - Length:
                max: 50
    constraints:
        - Callback: [isRoleScopePresentOnce]