services:
   - chill/database:latest

 
before_script:
   - composer config github-oauth.github.com $GITHUB_TOKEN
   - composer install
   - cp Tests/Fixtures/App/config/parameters.gitlab-ci.yml Tests/Fixtures/App/config/parameters.yml
   - php Tests/Fixtures/App/console --env=test cache:warmup
   - php Tests/Fixtures/App/console doctrine:migrations:migrate --env=test --no-interaction
   - php Tests/Fixtures/App/console doctrine:fixtures:load --env=test --no-interaction

test:php-5.6:
   stage: test
   image: chill/ci-image:php-5.6
   script: phpunit --testdox
test:php-7:
   stage: test
   image: chill/ci-image:php-7
   script: phpunit --testdox
