image: chill/standard-fpm
services:
   - postgres:9.4

 
before_script:
   - cd /tmp
   - apt-get install -qy git
   - composer install --dev
   - cp Tests/Fixtures/App/config/parameters.travis.yml Tests/Fixtures/App/config/parameters.yml
   - psql -c 'create database test0;' -U postgres
   - php Tests/Fixtures/App/console --env=test cache:warmup
   - php Tests/Fixtures/App/console doctrine:migrations:migrate --env=test --no-interaction
   - php Tests/Fixtures/App/console doctrine:fixtures:load --env=test --no-interaction

job1:
   stage: test
   script: phpunit --coverage-text