services:
   - postgres:9.4

 
before_script:
   - composer install --dev
   - cp Tests/Fixtures/App/config/parameters.gitlab-ci.yml Tests/Fixtures/App/config/parameters.yml
   - php Tests/Fixtures/App/console --env=test cache:warmup
   - php Tests/Fixtures/App/console doctrine:migrations:migrate --env=test --no-interaction
   - php Tests/Fixtures/App/console doctrine:fixtures:load --env=test --no-interaction

job1:
   stage: test
   script: phpunit --coverage-text