admin:
    path:     /
    defaults: { _controller: "ChillMainBundle:Center:index" }

admin_show:
    path:     /{id}/show
    defaults: { _controller: "ChillMainBundle:Center:show" }

admin_new:
    path:     /new
    defaults: { _controller: "ChillMainBundle:Center:new" }

admin_create:
    path:     /create
    defaults: { _controller: "ChillMainBundle:Center:create" }
    methods:  POST

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChillMainBundle:Center:edit" }

admin_update:
    path:     /{id}/update
    defaults: { _controller: "ChillMainBundle:Center:update" }
    methods:  [POST, PUT]
